### ISSUE TITLE
Issues Simplebroadcast 1.9.1

### ISSUE THREAD

**Issue by Sikatsu** [DominicLuidold/SimpleBroadcast#24]
The issue doesn't give errors so latest.log is not neccesary but here are the issues:

I'm trying to use json messages but it seems to have a bit of problems still.

1) Within /sb list it's not showing a number: http://prntscr.com/8m4eaz

2) Using /sb now 1 gives me this for a total of 3 times: http://prntscr.com/8m4ee3

3) When using Json messages, the prefix seems not to be working.

So i added it within the text:

"&a[VillagerCraft] &7Up-to-date blijven over de server? Check de &7website! Laatste update - &c29 september"

4) Also as you see, i had to use double &7 as somehow everything after the word ''de'' was white instead of gray. It seems that text on a second line will get white. But for every player depending on screensize this will be different so i can actually only be sure to fix this for myself.

Config: http://prntscr.com/98pl9u

**Comment by KingDome24** [comment]
Hello,

could you please upload the content of your config file to for example hastebin.com or pastebin.com? It's otherwise difficulty to exactly copy your messages. I please also need your Spigot build number which you're currently using (should get shown in the latest.log).

Kind regards,
KingDome24

**Comment by Sikatsu** [comment]
Hey KingDome24,

Here's the config file: http://pastebin.com/UuSapTQt
I'm using the latest spigot build from buildtools.jar: http://prntscr.com/98poii

**Comment by KingDome24** [comment]
Hello,

thanks for your additional information.
1) Is a known bug - I'll have a look if this is easy to fix or not.
2) Got fixed with release of v1.9.1
3) Same as 1)
4) JSON messages aren't designed to use the color codes of Minecraft. Instead you should use the "color" attribute. For example:
`JSON:{text:"This is an example","color":"yellow",hoverEvent:{action:show_text,value:[{text:"Example",color:blue}]}}`
Unfortunately the JSON colors are getting overridden by Minecraft color codes but you could add a separate text in the JSON string itself:
`JSON:["",{text:"Prefix","color":"yellow"},{text:"Text","color":"blue"}]`
This is a temporary fix until I can tell you more about these issues.

Kind regards,
KingDome24

**Comment by Sikatsu** [comment]
Thanks!

The plugin is driving me crazy. It now only will broadcast the firs one of the /sb list...

**Comment by KingDome24** [comment]
Hello,

have you edited your config file before the problem occurred? If so, could you please upload it again to pastebin.com?
Could you please also provide a screenshot of the mentioned behaviour?

Kind regards,
KingDome24

**Comment by KingDome24** [comment]
Hello,

I was able to fix this issue in v1.9.2 which will be a hotfix update. Therefore, your mentioned bugs are deferred for v1.9.3.

Kind regards,
KingDome24

**Comment by Sikatsu** [comment]
Hello KingDome24,

This update indeed fixed the issue. But, i ran into another issue.

When i use /sb now 7 (number 7 is NOT a json message) it will shoot the message multiple times:
http://prntscr.com/9d1ooy

As for the color codes, it indeed works now. But issue #1 and #3 are still present, probably something for 2.0?

Kind regards,

Sikatsu

**Comment by KingDome24** [comment]
Hello,

could you please attach your config file again? In your initial config I can only see 6 messages so I assume there's been some changes.
1) and 3) maybe get fixed in v1.9.3 or at the latest in v2.0 depending on the work that has to get done.

Kind regards,
KingDome24

**Comment by TekBob** [comment]
I'm having an issue.... When I edit the config, and reload or restart the server, it wouldn't update, help pleasE?


# This is the default config.yml of SimpleBroadcast.
# Plugin made by KingDome24.
# If you need help visit https://www.SimpleBroadcast.net
# Please be sure that all your messages are inside of single quotes!
# The update checking requires an Internet connection.

enabled: true

delay: 60 # time in seconds

prefix:
  enabled: true
  prefix: '&b&l[Broadcast]&l&f'
  
suffix:
  enabled: false
  suffix: '&d[v1.9.2]'

checkforupdates: true

randomizemessages: false

requiresonlineplayers: false

sendmessagestoconsole: false

messages:
- 'Join our website at: &a&lmonstagaming.co.uk&f&l! That's where you'll find most information.'

**Comment by KingDome24** [comment]
Hello,

you are not allowed to use single quotes (') within the message. Please use "%sq%" instead.
This will show a single quote when broadcasted.

Merry Christmas,
KingDome24
